### ISSUE TITLE
Add CSSconf Colombia 

### ISSUE THREAD

**Issue by Kriesse** [cssconf/cssconf.org#8]
🎉The newest addition to the family of events 🎉

@teffcode FYI, the spelling convention for CSSconf has been either `CSSconf` (e.g. like CSSconf EU, with lowercase c) or `CSSConf` (e.g. like CSSConf AU, with uppercase C), which one do you want to go for?

**Comment by teffcode** [comment]
Yeeeeei, thanks so much <3

We would like: CSSConf CO 😃

**Comment by teffcode** [comment]
Yeeeeei, thanks so much 💕

We would like: CSSConf CO 😃
